#!/usr/bin/env python3
"""Generate exiftool/ExifTool_config from the pan and copia ontologies.

Viewers that embed ExifTool (Xee³, XnView, digiKam …) show a namespace's
fields ONLY when the config declares each tag by name; a declared namespace
with undeclared tags shows an empty section. So every property in pan.ttl
and copia.ttl is declared here, and the file is regenerated whenever either
ontology changes:

    python3 exiftool/gen_config.py ontology/pan.ttl <path-to>/copia.ttl > exiftool/ExifTool_config
    cp exiftool/ExifTool_config ~/.ExifTool_config    # then RESTART the viewer
"""
import re, sys

def props(path, prefix):
    out = []
    for line in open(path):
        m = re.match(rf"^{prefix}:([A-Za-z0-9]+) a owl:(Datatype|Object)Property", line)
        if m:
            out.append(m.group(1))
    return sorted(set(out))

pan = props(sys.argv[1], "pan")
copia = props(sys.argv[2], "copia")
# In the file, identity and creation time are pan:id / pan:dateCreated
# (git-lex:id / git-lex:dateCreated in the graph).
pan = sorted(set(pan) | {"id", "dateCreated"})
# Nested shapes Pan writes: the thumbnail struct and the per-stage reference bags.
structs = {"thumbnail"}
bags = {"captionData", "poseData", "vectorData", "regionData"}

def tag_lines(names, skip=()):
    return "\n".join(f"    {n} => {{ }}," for n in names if n not in skip)

print(f"""# GENERATED by exiftool/gen_config.py from pan.ttl and copia.ttl — do not edit.
# Teaches ExifTool (and every viewer that embeds it: Xee³, XnView, digiKam …)
# the Pan and Copia XMP vocabularies, each with its own family-0 group, so they
# show as "pan:Image properties" and "copia:Moment properties" beside
# "XMP properties". Every tag is declared by name: a viewer shows a declared
# namespace's fields only when the tag itself is declared. A file carries only
# these two namespaces (goodlux, 2026-09-07). Install:
#   cp exiftool/ExifTool_config ~/.ExifTool_config
# then RESTART the viewer (ExifTool reads this once per process).

%panRef = (
    NAMESPACE   => {{ 'pan' => 'https://repolex.ai/ontology/pan/' }},
    STRUCT_NAME => 'PanRef',
    id => {{ }}, model => {{ }}, path => {{ }}, count => {{ }}, producedDate => {{ }},
);

%Image::ExifTool::UserDefined::pan = (
    GROUPS    => {{ 0 => 'pan:Image', 1 => 'pan:Image', 2 => 'Image' }},
    NAMESPACE => {{ 'pan' => 'https://repolex.ai/ontology/pan/' }},
    WRITABLE  => 'string',
{tag_lines(pan, structs | bags)}
    thumbnail => {{
        Struct => {{
            NAMESPACE   => {{ 'pan' => 'https://repolex.ai/ontology/pan/' }},
            STRUCT_NAME => 'PanThumb',
            path => {{ }}, width => {{ }}, height => {{ }},
        }},
    }},
{chr(10).join(f"    {b} => {{ List => 'Bag', Struct => \\%panRef }}," for b in sorted(bags))}
);

%Image::ExifTool::UserDefined::copia = (
    GROUPS    => {{ 0 => 'copia:Moment', 1 => 'copia:Moment', 2 => 'Image' }},
    NAMESPACE => {{ 'copia' => 'https://repolex.ai/ontology/copia/' }},
    WRITABLE  => 'string',
{tag_lines(copia)}
);

%Image::ExifTool::UserDefined = (
    'Image::ExifTool::XMP::Main' => {{
        pan   => {{ SubDirectory => {{ TagTable => 'Image::ExifTool::UserDefined::pan' }} }},
        copia => {{ SubDirectory => {{ TagTable => 'Image::ExifTool::UserDefined::copia' }} }},
    }},
);
1;""")
